parameters:
    app.locale: 'pt_BR'
    app.notifications.email_sender: anonymous@example.com

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            array $enabledLocales: '%kernel.enabled_locales%'
            string $defaultLocale: '%app.locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Bus\Expense\CreateExpenseCommandHandler:
        tags: [ 'messenger.message_handler' ]
    App\Event\Expense\ExpenseWasCreatedHandler:
        tags: [ 'messenger.message_handler' ]

    App\Bus\Income\CreateIncomeCommandHandler:
        tags: [ 'messenger.message_handler' ]
    App\Event\Income\IncomeWasCreatedHandler:
        tags: [ 'messenger.message_handler' ]
